fixtures:
  repositories:
    nodejs: "http://github.com/puppetlabs/puppetlabs-nodejs.git"
    stdlib: "http://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    cloudwatchd: "#{source_dir}"
